name: pj-suml-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - kedro
  - kedro-viz
  - autogluon
  - pydantic
  - fastapi
  - uvicorn
  - flask
  - requests
  - joblib
