version: '3.8'

services:
  kedro:
    build:
      context: ..
      dockerfile: docker/kedro/Dockerfile
    image: pjwstk-suml/kedro
    container_name: suml-kedro
    environment:
      - MODEL_URL=http://model:8001
    volumes:
      - ..:/home/kedro_docker
      - autogluon_models:/home/kedro_docker/AutogluonModels
    ports:
      - "8888:8888"
    networks:
      - pjwstk-suml

  model:
    build:
      context: ..
      dockerfile: docker/model/Dockerfile
    image: pjwstk-suml/model
    container_name: suml-model
    ports:
      - "8001:8001"
    networks:
      - pjwstk-suml

  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    image: pjwstk-suml/api
    container_name: suml-api
    environment:
      - CHAMPION_MODEL_URL=http://model:8001/champion_model.pkl
    volumes:
      - autogluon_models:/app/AutogluonModels
    ports:
      - "8000:8000"
    depends_on:
      - model
    networks:
      - pjwstk-suml

  ui:
    build:
      context: ..
      dockerfile: docker/ui/Dockerfile
    image: pjwstk-suml/ui
    container_name: suml-ui
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - pjwstk-suml

volumes:
  autogluon_models:

networks:
  pjwstk-suml:
    driver: bridge
